# Generated by Django 5.2.10 on 2026-01-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('navbar', 'Navbar'), ('sidebar', 'Sidebar'), ('footer', 'Footer')], default='navbar', max_length=20)),
                ('title', models.CharField(max_length=100, verbose_name='Menu nomi')),
                ('path', models.CharField(max_length=200, verbose_name='URL path')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class, masalan: fa-home', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_external', models.BooleanField(default=False, verbose_name='Tashqi havola')),
            ],
            options={
                'verbose_name': 'Menu element',
                'verbose_name_plural': 'Menu elementlari',
                'ordering': ['location', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MyLink.asia', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telegram', models.CharField(blank=True, help_text='@username yoki link', max_length=100)),
                ('analytics_code', models.TextField(blank=True, help_text='Google Analytics yoki boshqa analytics kod')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.AlterField(
            model_name='link',
            name='icon_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('whatsapp', 'WhatsApp'), ('telegram_number', 'Telegram Number'), ('phone', 'Phone Number'), ('linkedin', 'LinkedIn'), ('website', 'Website'), ('other', 'Other')], default='website', max_length=20),
        ),
    ]
