# Generated by Django 6.0.1 on 2026-01-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_menuitem_sitesettings_alter_link_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('whatsapp', 'WhatsApp'), ('telegram_number', 'Telegram Number'), ('phone', 'Phone Number'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('gmail', 'Gmail'), ('website', 'Website'), ('other', 'Other')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
