# Generated by Django 6.0.1 on 2026-01-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_alter_link_icon_type_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('x', 'X (Twitter)'), ('whatsapp', 'WhatsApp'), ('telegram_number', 'Telegram Number'), ('phone', 'Phone Number'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('gmail', 'Gmail'), ('yandex_map', 'Yandex Map'), ('google_map', 'Google Map'), ('website', 'Website'), ('other', 'Other')], default='website', max_length=20),
        ),
    ]
