# Generated by Django 6.0.6 on 2026-06-07 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_link_icon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(help_text='Email yoki Telegram', max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aloqa xabari',
                'verbose_name_plural': 'Aloqa xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_telegram_url',
            field=models.CharField(blank=True, help_text='Yordam tugmasi/aloqa uchun Telegram havola, masalan https://t.me/username', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Aloqa xabarlarini guruhga yuborish uchun bot tokeni', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Xabarlar yuboriladigan guruh/chat ID', max_length=50),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('body', models.TextField(help_text='HTML yoki oddiy matn')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog postlar',
                'ordering': ['-published_at'],
                'unique_together': {('slug', 'language')},
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('about', 'Biz haqimizda'), ('privacy', 'Maxfiylik'), ('terms', 'Shartlar')], max_length=20)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='HTML yoki oddiy matn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statik sahifa',
                'verbose_name_plural': 'Statik sahifalar',
                'ordering': ['slug', 'language'],
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
