# Generated by Django 6.0.2 on 2026-06-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_seed_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
