# Generated by Django 6.0.6 on 2026-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_business_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
