# Generated by Django 6.0.6 on 2026-06-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_business_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('text', 'Matn')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/')),
                ('video', models.FileField(blank=True, null=True, upload_to='blocks/videos/')),
                ('embed_url', models.CharField(blank=True, help_text='YouTube/Instagram embed havolasi', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Kontent blok',
                'verbose_name_plural': 'Kontent bloklar',
                'ordering': ['order'],
            },
        ),
    ]
