# Generated by Django 6.0.6 on 2026-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('restoran', 'Restoran (FLAME)'), ('moda', 'Moda (editorial)'), ('klinika', 'Klinika (teal)'), ('avto', 'Avto (carbon)'), ('fitnes', 'Fitnes (lime)')], default='classic', max_length=20),
        ),
    ]
