# Generated by Django 6.0.6 on 2026-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_business_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='theme',
            field=models.CharField(choices=[('default', 'Default (indigo)'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('noir', 'Noir'), ('rose', 'Rose'), ('sunset', 'Sunset')], default='default', max_length=20),
        ),
    ]
