# Generated by Django 6.0.6 on 2026-06-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_businessmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['order', '-published_at'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog postlar'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ro'yxatdagi o'rni — kichigi birinchi chiqadi", verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name="Landing'da ko'rsatish"),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefon raqam', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact',
            field=models.CharField(blank=True, help_text='Email yoki Telegram', max_length=200),
        ),
    ]
