# Generated by Django 6.0.6 on 2026-06-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_alter_blogpost_options_blogpost_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, help_text="Bo'sh qoldirsangiz post chiqmaydi"),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=models.TextField(blank=True, help_text="Bo'sh qoldirsangiz sahifa 'tez orada' deb ko'rsatiladi"),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
