# Generated by Django 6.0.6 on 2026-06-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_alter_blogpost_body_alter_blogpost_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcorder',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_orders', to='businesses.business', verbose_name='Biznes (ixtiyoriy)'),
        ),
    ]
