# Generated by Django 6.0.6 on 2026-07-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_alter_link_icon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_sections', to='businesses.business')),
            ],
            options={
                'verbose_name': "Media bo'lim",
                'verbose_name_plural': "Media bo'limlar",
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='businesses.mediasection'),
        ),
    ]
