# Generated by Django 6.0.6 on 2026-07-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0021_group_blocks_into_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='theme_mode',
            field=models.CharField(blank=True, choices=[('dark', 'Dark'), ('light', 'Light')], default='', max_length=5),
        ),
    ]
