# Generated by Django 6.0.6 on 2026-08-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0022_business_theme_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('x', 'X (Twitter)'), ('whatsapp', 'WhatsApp'), ('telegram_number', 'Telegram Number'), ('phone', 'Phone Number'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('gmail', 'Gmail'), ('yandex_map', 'Yandex Map'), ('google_map', 'Google Map'), ('steam', 'Steam'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('twitch', 'Twitch'), ('discord', 'Discord'), ('pinterest', 'Pinterest'), ('website', 'Website'), ('other', 'Other')], default='website', max_length=20),
        ),
    ]
