# Generated by Django 6.0.6 on 2026-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0023_alter_link_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcorder',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name="Jami summa (so'm)"),
        ),
        migrations.AddField(
            model_name='nfcorder',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langan"),
        ),
        migrations.AddField(
            model_name='nfcorder',
            name='offer_accepted',
            field=models.BooleanField(default=False, help_text='Foydalanuvchi buyurtma berishda ommaviy oferta shartlarini tasdiqlagan.', verbose_name='Oferta qabul qilingan'),
        ),
        migrations.AddField(
            model_name='nfcorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfcorder',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name="1 dona narxi (so'm)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nfc_price',
            field=models.PositiveIntegerField(default=0, help_text="Foydalanuvchi buyurtma berishdan oldin shu narxni ko'radi; to'lov summasi = narx x soni. 0 bo'lsa to'lov so'ralmaydi.", verbose_name="NFC vizitka narxi (1 dona, so'm)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offer_pdf',
            field=models.FileField(blank=True, help_text="Yuklansa — sayt shu faylni ko'rsatadi; bo'sh bo'lsa standart oferta ishlatiladi.", null=True, upload_to='docs/', verbose_name='Ommaviy oferta (PDF)'),
        ),
    ]
