# Generated by Django 6.0.6 on 2026-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0024_nfcorder_amount_nfcorder_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Yuridik manzil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='Ofertada ko\'rsatiladi, masalan: "MyLink Group" MChJ', max_length=200, verbose_name='Tashkilot nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_tin',
            field=models.CharField(blank=True, max_length=20, verbose_name='STIR (INN)'),
        ),
    ]
