# Generated by Django 6.0.6 on 2026-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0025_sitesettings_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcorder',
            name='status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('new', 'Yangi'), ('processing', 'Jarayonda'), ('done', 'Bajarildi'), ('canceled', 'Bekor')], default='new', max_length=12),
        ),
    ]
