# Generated by Django 6.0.6 on 2026-08-11 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0023_alter_link_icon_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ro'yxatda ko'rinadigan nom", max_length=100)),
                ('button_label', models.CharField(blank=True, default='', help_text="Sahifadagi tugma matni, masalan 'Menyu'", max_length=30)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='catalog/banners/')),
                ('currency', models.CharField(default="so'm", max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(blank=True, help_text="Qaysi biznes sahifasida ko'rsatiladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog', to='businesses.business')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Katalog',
                'verbose_name_plural': 'Kataloglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.catalog')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text="Narx (UZS so'm)")),
                ('old_price', models.PositiveIntegerField(blank=True, help_text="Chegirmadan oldingi narx (ustidan chizib ko'rsatiladi)", null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.catalogcategory')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/items/')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='catalog/items/thumbs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
