# Generated by Django 6.0.6 on 2026-08-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='card_style',
            field=models.CharField(choices=[('list', 'Ro‘yxat'), ('grid', 'Grid')], default='list', max_length=5, verbose_name='Karta stili'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='theme',
            field=models.CharField(choices=[('mylink', 'MyLink (indigo)'), ('tandir', 'Tandir (issiq)'), ('anor', 'Anor (qizil)'), ('rayhon', 'Rayhon (yashil)'), ('oltin', 'Oltin tun'), ('chinni', 'Chinni (ko‘k)'), ('qaymoq', 'Qaymoq (neytral)'), ('tut', 'Tut (siyoh)')], default='mylink', max_length=12, verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='theme_mode',
            field=models.CharField(choices=[('dark', 'Tungi'), ('light', 'Kunduzgi')], default='dark', max_length=5, verbose_name='Muhit'),
        ),
    ]
