# Generated by Django 6.0.6 on 2026-08-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_card_style_grid_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='cart_enabled',
            field=models.BooleanField(default=False, help_text="Mijoz mahsulot yig'ib, buyurtma ro'yxatini yubora oladi", verbose_name='Savatcha'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='order_enabled',
            field=models.BooleanField(default=False, verbose_name='Buyurtma tugmasi'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='order_label',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Buyurtma tugmasi matni'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='order_link',
            field=models.CharField(blank=True, default='', help_text='Telegram (@nom), WhatsApp raqami yoki istalgan havola', max_length=200, verbose_name='Buyurtma havolasi'),
        ),
    ]
