"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+-#fg#$&j3rw3h)4)h3g$k9&nsooab1y$il274qpu0jn$umo1q')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'mylink.asia', 'www.mylink.asia', 'api.mylink.asia',
    # Staging (client testing, deployed from the dev branch)
    'dev.mylink.asia', 'api-dev.mylink.asia',
    '161.97.176.239', 'localhost', '127.0.0.1',
]


# Application definition
INSTALLED_APPS = [
    'jazzmin',  # Enabled Jazzmin admin theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'users',
    'businesses',
    'billing',
]

# Jazzmin Admin Theme Settings
JAZZMIN_SETTINGS = {
    # Title and branding
    "site_title": "MyLink.asia Admin",
    "site_header": "MyLink.asia",
    "site_brand": "MyLink.asia",
    "site_logo": "brand/appicon-192.png",
    "site_icon": "brand/appicon-64.png",
    "welcome_sign": "MyLink.asia Admin Paneliga xush kelibsiz!",
    "copyright": "MyLink.asia © 2026",
    
    # Search model
    "search_model": ["users.CustomUser", "businesses.Business"],
    
    # Top Menu Links
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Sayt", "url": "/", "new_window": True},
    ],
   # User menu
    "usermenu_links": [
        {"model": "auth.user"}
    ],
    
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Icons (Font Awesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "users.CustomUser": "fas fa-user-circle",
        "businesses.Business": "fas fa-store",
        "businesses.Link": "fas fa-link",
        "businesses.MenuItem": "fas fa-bars",
        "businesses.SiteSettings": "fas fa-cog",
    },
    
    # Related Modal
    "related_modal_active": True,
    
    # UI Customization
    "custom_css": None,
    # Fixes change-form tabs/collapsibles under Jazzmin 3.0.2's BS4-markup +
    # bundled-BS5 mismatch (see businesses/static/jazzmin_fix/tabs.js).
    "custom_js": "jazzmin_fix/tabs.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    # Change view options
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-primary",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


import dj_database_url

# ... (imports)

# Database
# Use SQLite by default, but override with DATABASE_URL if present (e.g. in production)
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.auth.ExpiringTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Umumiy API Rate Limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',   # Anonim foydalanuvchilar: 100 so'rov/soat
        'user': '1000/hour',  # Autentifikatsiya qilingan: 1000 so'rov/soat
    },
}

# CORS settings - Production
CORS_ALLOWED_ORIGINS = [
    "https://mylink.asia",
    "https://www.mylink.asia",
    "https://dev.mylink.asia",   # staging frontend
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True

# Security settings for HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    'https://mylink.asia',
    'https://api.mylink.asia',
    'https://www.mylink.asia',
    'https://dev.mylink.asia',      # staging
    'https://api-dev.mylink.asia',  # staging API (admin panel)
]


# Cache configuration - Database cache for production
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
    }
}

# Email (SMTP) configuration. Falls back to console backend in dev.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'  # port 465 uchun
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'MyLink <no-reply@mylink.asia>')

# Frontend base URL (used for password-reset links, etc.)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Click (click.uz) SHOP API — plan checkout. Empty in dev → the buy endpoint
# answers 503 click_not_configured and the UI hides the pay button.
CLICK_SERVICE_ID = os.getenv('CLICK_SERVICE_ID', '')
CLICK_MERCHANT_ID = os.getenv('CLICK_MERCHANT_ID', '')
CLICK_SECRET_KEY = os.getenv('CLICK_SECRET_KEY', '')

# Auth token sliding-expiry window (days)
TOKEN_EXPIRE_DAYS = int(os.getenv('TOKEN_EXPIRE_DAYS', '7'))

# Google OAuth client id (used to verify Google sign-in ID tokens)
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')


# Jazzmin + Django 5.2 compatibility patch (format_html bug fix)
from config.jazzmin_patch import apply_jazzmin_patch
apply_jazzmin_patch()
