# Generated by Django 6.0.6 on 2026-06-06 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('oddiy', 'Oddiy'), ('pro', 'Pro')], max_length=10)),
                ('period', models.CharField(choices=[('onetime', 'Bir martalik'), ('1m', '1 oy'), ('6m', '6 oy'), ('1y', '1 yil')], max_length=10)),
                ('price', models.PositiveIntegerField(help_text="Narx (UZS so'm)")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarif narxi',
                'verbose_name_plural': 'Tarif narxlari',
                'ordering': ['tier', 'period'],
                'unique_together': {('tier', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('oddiy', 'Oddiy'), ('pro', 'Pro')], max_length=10)),
                ('period', models.CharField(blank=True, choices=[('onetime', 'Bir martalik'), ('1m', '1 oy'), ('6m', '6 oy'), ('1y', '1 yil')], max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=10)),
                ('source', models.CharField(choices=[('payment', 'Payment'), ('promo', 'Promo'), ('referral', 'Referral'), ('manual', 'Manual'), ('gift', 'Gift')], default='manual', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
