# Generated by Django 6.0.2 on 2026-06-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Foydalanuvchi kiritadigan kod (avto katta harf)', max_length=40, unique=True)),
                ('grant_tier', models.CharField(choices=[('free', 'Free'), ('oddiy', 'Oddiy'), ('pro', 'Pro')], default='pro', max_length=10, verbose_name='Beriladigan tarif')),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text="Necha kunga beriladi. Bo'sh = umrbod (lifetime).", null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text="Jami necha marta ishlatilishi mumkin. Bo'sh = cheksiz.", null=True)),
                ('redeemed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('once_per_user', models.BooleanField(default=True, help_text='Bitta foydalanuvchi faqat bir marta ishlata oladi')),
                ('valid_until', models.DateTimeField(blank=True, help_text="Shu sanadan keyin kod ishlamaydi. Bo'sh = muddatsiz.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, help_text='Ichki izoh (kampaniya nomi va h.k.)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.promocode')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to='billing.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promokod ishlatilishi',
                'verbose_name_plural': 'Promokod ishlatilishlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
