# Generated by Django 6.0.6 on 2026-06-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_referralreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Texnik nom: free, oddiy, pro, biznes ...', max_length=20, unique=True)),
                ('name', models.CharField(help_text="Ko'rinadigan nom", max_length=50)),
                ('rank', models.PositiveIntegerField(default=0, help_text="Kattaroq = kuchliroq. Eng yuqori rankli faol obuna g'olib bo'ladi.")),
                ('is_default', models.BooleanField(default=False, help_text="Obunasiz foydalanuvchilar shu tarifda bo'ladi (faqat bittasi).")),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text="Narxlar sahifasida ko'rsatilsinmi.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Narxlar sahifasidagi tartib.')),
                ('profile_limit', models.PositiveIntegerField(default=1, verbose_name='Sahifalar soni')),
                ('templates', models.PositiveIntegerField(default=1, verbose_name='Shablonlar soni')),
                ('color_edit', models.BooleanField(default=False, verbose_name='Rang tahrirlash')),
                ('banners', models.PositiveIntegerField(default=0, verbose_name='Media bloklar soni')),
                ('banner_video', models.BooleanField(default=False, verbose_name='Video blok')),
                ('analytics', models.CharField(choices=[('none', "Yo'q"), ('partial', 'Qisman'), ('full', "To'liq")], default='none', max_length=10)),
                ('qr', models.CharField(choices=[('none', "Yo'q"), ('png', 'PNG'), ('full', 'PNG + PDF + vizitka')], default='none', max_length=10, verbose_name='QR / vizitka')),
                ('branding_removed', models.BooleanField(default=False, verbose_name='Brending olib tashlanadi')),
                ('verified_badge', models.BooleanField(default=False, verbose_name='Tasdiq belgisi')),
                ('team', models.BooleanField(default=False, verbose_name='Jamoa / rollar')),
            ],
            options={
                'verbose_name': 'Tarif (Plan)',
                'verbose_name_plural': 'Tariflar (Plans)',
                'ordering': ['order', 'rank'],
            },
        ),
        migrations.AlterField(
            model_name='planprice',
            name='tier',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='grant_tier',
            field=models.CharField(default='pro', max_length=20, verbose_name='Beriladigan tarif'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(max_length=20),
        ),
    ]
