# Generated by Django 6.0.6 on 2026-06-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_seed_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='planprice',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.plan'),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='tier',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
