# Generated by Django 6.0.6 on 2026-06-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_link_prices_to_plans'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planprice',
            unique_together={('plan', 'period')},
        ),
    ]
