# Generated by Django 6.0.6 on 2026-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='catalog',
            field=models.BooleanField(default=False, verbose_name='Katalog / web-menyu'),
        ),
    ]
