# Generated by Django 6.0.6 on 2026-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_backfill_pro_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True, help_text="O'chirilsa tarif landing/narxlar sahifasida chiqmaydi — faqat adminlar obuna berishda ishlata oladi.", verbose_name="Mijozlarga ko'rinadi"),
        ),
    ]
