# Generated by Django 6.0.6 on 2026-09-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_plan_is_public'),
        ('businesses', '0024_nfcorder_amount_nfcorder_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='kind',
            field=models.CharField(choices=[('plan', 'Tarif'), ('nfc', 'NFC vizitka')], default='plan', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='nfc_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='businesses.nfcorder', verbose_name='NFC buyurtma'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.CharField(blank=True, choices=[('onetime', 'Bir martalik'), ('1m', '1 oy'), ('6m', '6 oy'), ('1y', '1 yil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='tier',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
