from django.urls import path
from .views import (
    BusinessListCreateView,
    BusinessDetailView,
    BusinessToggleLockView,
    BusinessTogglePinView,
    BusinessAssetView,
    MembershipListCreateView,
    MembershipDetailView,
    ContentBlockListCreateView,
    ContentBlockDetailView,
    ContentBlockReorderView,
    TrackView,
    BusinessAnalyticsView,
    NfcOrderListCreateView,
    PublicBusinessView,
    PublicStatsView,
    PublicSettingsView,
    ContactCreateView,
    StaticPageView,
    BlogListView,
    BlogDetailView,
)

urlpatterns = [
    path('businesses/', BusinessListCreateView.as_view()),
    path('businesses/<slug:path>/lock/', BusinessToggleLockView.as_view()),
    path('businesses/<slug:path>/pin/', BusinessTogglePinView.as_view()),
    path('businesses/<slug:path>/qr.png', BusinessAssetView.as_view(), {'fmt': 'qr_png'}),
    path('businesses/<slug:path>/qr.pdf', BusinessAssetView.as_view(), {'fmt': 'qr_pdf'}),
    path('businesses/<slug:path>/card.pdf', BusinessAssetView.as_view(), {'fmt': 'card_pdf'}),
    path('businesses/<slug:path>/blocks/reorder/', ContentBlockReorderView.as_view()),
    path('businesses/<slug:path>/blocks/', ContentBlockListCreateView.as_view()),
    path('businesses/<slug:path>/analytics/', BusinessAnalyticsView.as_view()),
    path('businesses/<slug:path>/members/', MembershipListCreateView.as_view()),
    path('members/<int:pk>/', MembershipDetailView.as_view()),
    path('blocks/<int:pk>/', ContentBlockDetailView.as_view()),
    path('track/', TrackView.as_view()),
    path('businesses/<slug:path>/', BusinessDetailView.as_view()),
    path('contact/', ContactCreateView.as_view()),
    path('nfc/orders/', NfcOrderListCreateView.as_view()),
    path('blog/', BlogListView.as_view()),
    path('blog/<slug:slug>/', BlogDetailView.as_view()),
    path('pages/<slug:slug>/', StaticPageView.as_view()),
    # public/stats and public/settings must precede public/<slug:path>/ so they
    # aren't captured as a business path.
    path('public/stats/', PublicStatsView.as_view()),
    path('public/settings/', PublicSettingsView.as_view()),
    path('public/<slug:path>/', PublicBusinessView.as_view()),
]
