# Generated by Django 6.0.6 on 2026-06-06 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def null_empty_emails(apps, schema_editor):
    """Existing OTP users have email='' which would collide under a unique
    constraint. Convert empty strings to NULL (NULLs are exempt from UNIQUE)."""
    User = apps.get_model('users', 'CustomUser')
    User.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        # 1) Relax email to nullable (no unique yet) so we can null-out '' values.
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        # 2) Convert existing empty emails to NULL.
        migrations.RunPython(null_empty_emails, migrations.RunPython.noop),
        # 3) Now it is safe to add the unique constraint.
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
